In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\User\\Downloads\\Video Game Sales dataset\\Video_Games_Sales_as_at_22_Dec_2016.csv")

In [4]:
df.shape

(16719, 16)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  str
 1   Platform         16719 non-null  str
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  str
 4   Publisher        16665 non-null  str
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       7590 non-null   float64
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  str
 15  Rating           9950 non-null   str
dtypes: float64(10), str(6)
memory usage: 2.0 MB

In [6]:
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.describe()

,Year_of_Release,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count
count,16450.000000,16719.000000,16719.000000,16719.000000,16719.000000,16719.000000,8137.000000,8137.000000,7590.000000,7590.000000
mean,2006.487356,0.263330,0.145025,0.077602,0.047332,0.533543,68.967679,26.360821,7.125046,162.229908
std,5.878995,0.813514,0.503283,0.308818,0.186710,1.547935,13.938165,18.980495,1.500006,561.282326
min,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,0.000000,4.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000,60.000000,12.000000,6.400000,10.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000,71.000000,21.000000,7.500000,24.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,0.470000,79.000000,36.000000,8.200000,81.000000
max,2020.000000,41.360000,28.960000,10.220000,10.570000,82.530000,98.000000,113.000000,9.700000,10665.000000

Finding missing values

In [8]:
df.isnull().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         9129
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [9]:
df1=df.copy()

In [10]:
#dropping null values from name column
df.dropna(subset=['Name'], inplace=True)

In [11]:
df1.shape

(16719, 16)

In [12]:
df.isna().sum()

Name                  0
Platform              0
Year_of_Release     269
Genre                 0
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8580
Critic_Count       8580
User_Score         9127
User_Count         9127
Developer          6621
Rating             6767
dtype: int64

In [13]:
df.shape

(16717, 16)

In [14]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

In [15]:
print(
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_Percentage", ascending=False)
)

                 Missing_Count  Missing_Percentage
User_Count                9127               54.60
User_Score                9127               54.60
Critic_Count              8580               51.32
Critic_Score              8580               51.32
Rating                    6767               40.48
Developer                 6621               39.61
Year_of_Release            269                1.61
Publisher                   54                0.32

In [16]:
df['Publisher']=df.Publisher.fillna("Unknown")

Since just 1.61% of data is missing in year_of_release we remove those rows containing missing values

In [19]:
df=df.dropna(subset=['Year_of_Release']).copy()

In [20]:
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})
print(
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_Percentage", ascending=False)
)

              Missing_Count  Missing_Percentage
User_Count             8985               54.63
User_Score             8985               54.63
Critic_Count           8465               51.47
Critic_Score           8465               51.47
Rating                 6679               40.61
Developer              6541               39.77

In [23]:
df['Developer']=df.Developer.fillna("Unknown")

In [25]:
df['Rating']=df.Rating.fillna("Unknown")

In [26]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})
print(
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_Percentage", ascending=False)
)

              Missing_Count  Missing_Percentage
User_Count             8985               54.63
User_Score             8985               54.63
Critic_Count           8465               51.47
Critic_Score           8465               51.47

In [44]:
df['User_Score'].value_counts(dropna=False)

User_Score
NaN    8985
7.8     322
8.0     285
8.2     276
8.3     252
       ...
0.6       2
0.9       2
1.0       2
0.0       1
9.7       1
Name: count, Length: 96, dtype: int64

In [45]:
print(df["User_Score"].value_counts(dropna=False).tail(15))

User_Score
1.9    2
9.6    2
1.1    2
0.3    2
1.5    2
0.7    2
2.3    2
0.5    2
1.3    2
0.2    2
0.6    2
0.9    2
1.0    2
0.0    1
9.7    1
Name: count, dtype: int64

In [46]:

# Check whether User_Score contains non-numeric values
print(
    df.loc[
        df["User_Score"].notna()
        & pd.to_numeric(df["User_Score"], errors="coerce").isna(),
        "User_Score"
    ].unique()
)

# Check the data type
print(df["User_Score"].dtype)

[]
float64

In [47]:
print("Missing user scores:", df["User_Score"].isnull().sum())
print("Data type:", df["User_Score"].dtype)
print("Number of rows:", len(df))

Missing user scores: 8985
Data type: float64
Number of rows: 16448

In [48]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})
print(
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_Percentage", ascending=False)
)

              Missing_Count  Missing_Percentage
User_Count             8985               54.63
User_Score             8985               54.63
Critic_Count           8465               51.47
Critic_Score           8465               51.47

In [49]:
df[["User_Score", "User_Count", "Critic_Score", "Critic_Count"]].isna().sum()

User_Score      8985
User_Count      8985
Critic_Score    8465
Critic_Count    8465
dtype: int64

In [50]:
df["User_Score"].isna().sum(), df["User_Count"].isna().sum()

(np.int64(8985), np.int64(8985))

In [51]:
df[["User_Score", "User_Count", "Critic_Score", "Critic_Count"]].isna().corr()

              User_Score  User_Count  Critic_Score  Critic_Count
User_Score      1.000000    1.000000      0.799455      0.799455
User_Count      1.000000    1.000000      0.799455      0.799455
Critic_Score    0.799455    0.799455      1.000000      1.000000
Critic_Count    0.799455    0.799455      1.000000      1.000000

In [52]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (df.isna().mean() * 100).round(2)
})

print(missing_summary[missing_summary["Missing_Count"] > 0])

              Missing_Count  Missing_Percentage
Critic_Score           8465               51.47
Critic_Count           8465               51.47
User_Score             8985               54.63
User_Count             8985               54.63

In [53]:
review_cols = [
    "User_Score",
    "User_Count",
    "Critic_Score",
    "Critic_Count"
]

print(df[review_cols].dtypes)
print(df[review_cols].isna().sum())

User_Score      float64
User_Count      float64
Critic_Score    float64
Critic_Count    float64
dtype: object
User_Score      8985
User_Count      8985
Critic_Score    8465
Critic_Count    8465
dtype: int64

In [54]:
print("Dataset shape:", df.shape)

Dataset shape: (16448, 16)

## checking for duplicates

In [56]:
print("Duplicate rows:",df.duplicated().sum())

Duplicate rows: 0

This shows that there are no duplicated rows in the dataset